### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by soupi** [soupi/hablog#1]
Possibly using [rss](https://hackage.haskell.org/package/rss)

**Comment by tfausak** [comment]
:+1: I was just looking for this on your blog.

**Comment by soupi** [comment]
It might be a while before I'll start working on this though :)

**Comment by soupi** [comment]
Done in 43fa1dafd82cdcb28ec2bc1f6067fca7ca3e682b. hopefully correctly!

**Comment by tfausak** [comment]
Looks great, thanks!
