### ISSUE TITLE
why the html code cannot be parsed?

### ISSUE THREAD

**Issue by luckypoem** [soupi/hablog#2]
hi.

i setup a blog : http://surmount.biz.st:6688 ,but why in the post http://surmount.biz.st:6688/post/2016/08/11%2016:48/magic-thief , the html code cannot be parsed?
(i inserted some html code in its source md file )

how to fix it?

and this blog app doesn't support pagination?

**Comment by soupi** [comment]
Can you share your page? this seems to work for me:

``` md
title: test
authors: test
route: test
date: 2016-08-11
tags: test

---

<h2>Hello world</h2>

<p>This tests seems to be working</p>
```

I am not very familiar with what pagination is, but I think it is not supported currently.

**Comment by luckypoem** [comment]
hi.

it's some youtube video code:
title: 绝色神偷
authors: brite
route: magic-thief
date: 2016-08-11 16:48

## tags: misc1, misc2, misc3, misc4

<p><iframe width="640" height="360" src="https://www.youtube.com/embed/NQ5hofOsntE" frameborder="0" allowfullscreen></iframe>

**Comment by luckypoem** [comment]
the youtube code is omitted by github

**Comment by soupi** [comment]
Can you post it as a [code block](https://guides.github.com/features/mastering-markdown/)?
