### ISSUE TITLE
Add Pandoc Markdown support

### ISSUE THREAD

**Issue by Vekkq** [soupi/hablog#3]
Hi, I wonder a bit, why Pandoc wasn't used in first place. Pandoc Markdown provides some very useful extensions to Markdown, so I guess it would be nice to have it.

**Comment by soupi** [comment]
I wasn't aware of pandoc when I first started this project, but three issues I have with pandoc that don't justify replacing what's already works is:

- It's GPL
- It's really big and has lots of dependencies
- I don't use any of it's features currently

Feel free to fork!
