### ISSUE TITLE
Which page do the posts aggregate on?

### ISSUE THREAD

**Issue by trosel** [soupi/hablog#4]
Do all the posts automatically get aggregated on a /posts/ page?

Is this configured somewhere?

**Comment by soupi** [comment]
[my blog](https://gilmi.me/) runs on hablog. You can look at this rendered there.

* markdown files that go under the `_posts` directory will be shown under `Posts` on the front page.
* markdown files that go under the `_pages` directory will be shown under `Pages` on the front page.

I hope this answers your question. If not please elaborate.
